services:
  db:
    image: postgres:16
    container_name: nexora_db
    environment:
      POSTGRES_USER: nexora_user
      POSTGRES_PASSWORD: nexora_pass
      POSTGRES_DB: nexora_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: nexora_backend
    environment:
      DATABASE_URL: postgresql://nexora_user:nexora_pass@db:5432/nexora_db
      JWT_SECRET_KEY: change_this_to_something_random_later
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: nexora_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: