services:
  db:
    image: postgres:16
    container_name: nexora_db
    environment:
      POSTGRES_USER: nexora_user
      POSTGRES_PASSWORD: nexora_pass
      POSTGRES_DB: nexora_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: